type: object
properties:
  id:
    type: string
    description: A unique identifier for this particular occurrence of the error.
  status:
    type: string
    description: The HTTP status code applicable to this error.
  code:
    type: string
    description: |
      An application-specific error code:
        - `ADMIN-400-1` - Invalid page cursor
        - `ADMIN-400-2` - Invalid domain identifier
        - `ADMIN-400-3` - Invalid time date
        - `ADMIN-400-4` - Invalid resource
        - `ADMIN-404-1` - Unknown resource
        - `ADMIN-404-2` - Organization not found
        - `ADMIN-404-3` - Domain not found
        - `ADMIN-404-4` - Event not found
        - `ADMIN-404-5` - Policy not found
        - `ADMIN-405-1` - Method not supported
        - `ADMIN-429-1` - Limit exceeded
        - `ADMIN-500-1` - Internal error
  title:
    type: string
    description: Human-readable summary of the error
  detail:
    type: string
    description: Human-readable explanation specific to this occurrence of the error.
